#!/bin/bash

# Оновлення системи та встановлення Apache2
apt update -y
apt install -y apache2

# Створення власної головної сторінки
rm -rf /var/www/html/index.html #видалення старої сторінки
touch /var/www/html/index.html #створення файлу
echo "Hello It-Universe, generated by autoscript <br> $(lsb_release -d)" >> /var/www/html/index.html #запис у файл
